### PR TITLE
Restructure project

### PR DESCRIPTION
**Pull request by jeremystucki**

### CODE REVIEW

**Comment by jeremystucki** [comment]
@SirRade Could you please add the library to the  Visual Studio Project?

**Comment by jeremystucki** [comment]
@Mafii Could you please configure the visual studio project?

It should build the library first and then build the example project with the library. (Like in cmake)

**Review by jeremystucki — COMMENTED** [review]
Everything seems to be ok

**Review by janhohenheim — CHANGES_REQUESTED** [review]
I want memes

**Comment by jeremystucki** [comment]
@SirRade @Mafii Is the current folder structure ok?

**Review by janhohenheim — APPROVED** [review]

**Pull request merged**
